### ISSUE TITLE
Isaac Racing Mods could not automatically close Isaac

### ISSUE THREAD

**Issue by mikeaccelm** [Zamiell/isaac-racing-mods#2]
[isaac-racing-mods-error-log.txt](https://github.com/Zamiell/isaac-racing-mods/files/333278/isaac-racing-mods-error-log.txt)

**Comment by Zamiell** [comment]
Here's the contents of that txt file:

```
06/25/2016 16:40:17 - Isaac Racing Mods could not automatically close Isaac:

Traceback (most recent call last):
  File "site-packages\psutil\_pswindows.py", line 488, in wrapper
  File "site-packages\psutil\_pswindows.py", line 602, in kill
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "program.py", line 200, in launch_isaac
  File "site-packages\psutil\__init__.py", line 326, in wrapper
  File "site-packages\psutil\__init__.py", line 1189, in kill
  File "site-packages\psutil\_pswindows.py", line 491, in wrapper
psutil.AccessDenied: psutil.AccessDenied (pid=10524, name='isaac-ng.exe')
```

As you can see, it is complaining about not being able to automatically close Isaac, saying that "Access is denied". Thus, I suspect that it has something do with your Windows permissions.

Some things to try, any of which individually might solve the problem:
1. Run the Isaac Racing Mods program as an administrator.
2. Close the game yourself manually so that the mod doesn't have to do it for you.
3. Don't run the game with superuser/administrative privileges (there's no need for it).
4. Make sure that the local Windows user that you are running as has general administrative rights on your computer.

**Comment by mikeaccelm** [comment]
The first solution is what worked, thank you.
